-- Step 2: Row Level Security (RLS) の有効化
-- Supabaseセキュリティ警告修正 - 第2段階

-- 主要テーブルでRLSを有効化
ALTER TABLE stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE credit_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_bulletins ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE lesson_schools ENABLE ROW LEVEL SECURITY;
ALTER TABLE lesson_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE flower_lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE region_categories ENABLE ROW LEVEL SECURITY;
